CREATE TABLE RUTAS (
  RUTA STRING,
  HOJA_RUTA STRING,
  KM DOUBLE,
  CONDUCTOR STRING
);
  
INSERT INTO RUTAS VALUES
('A','0001',100, 'P'),
('B','0002',22 , 'B'),
('C','0002',177, 'R'),
('D','0011',109, 'E')


SELECT * FROM RUTAS ORDER BY KM ASC;

SELECT HOJA_RUTA,
       SUM(KM) AS TOTAL_KM_HOJARUTA,
       COUNT(*) AS CONTEO,
       GROUP_CONCAT(RUTA, '-') AS CONJUNTO_RUTAS_POR_HOJA
FROM RUTAS GROUP BY HOJA_RUTA;
